"""
AegisTrap Unified Structured Logging System
=============================================
Provides JSON-formatted structured logging for all honeypot interactions.
Every event is written as a flat JSON entry to a rolling log file suitable
for SIEM/Elastic ingestion.

Log Format (per entry):
- timestamp (ISO 8601)
- attacker_ip
- attacker_port
- service_targeted (SSH, HTTP, FTP, Telnet)
- input_received (exact command, HTTP payload, or login credentials)
- ai_response (output generated by Ollama)
- session_id (UUID4 per connection)
"""

import os
import json
import asyncio
import logging
from datetime import datetime, timezone
from typing import Optional

import aiofiles

from config import LOG_DIR, LOG_FILE, LOG_MAX_SIZE_MB
from aegistrap.core.session_manager import AttackerSession

logger = logging.getLogger("aegistrap.logger")


class StructuredLogger:
    """
    Async-capable structured JSON logger.
    Writes flat JSON entries to a rolling log file on disk.
    Thread-safe via asyncio Lock for concurrent write operations.
    """

    def __init__(
        self,
        log_file: str = LOG_FILE,
        log_dir: str = LOG_DIR,
        max_size_mb: int = LOG_MAX_SIZE_MB,
    ):
        self._log_file = log_file
        self._log_dir = log_dir
        self._max_size_bytes = max_size_mb * 1024 * 1024
        self._lock = asyncio.Lock()
        self._event_count = 0
        self._initialized = False

    async def initialize(self) -> None:
        """
        Initialize the logging system.
        Creates the log directory if it doesn't exist and verifies write access.
        """
        if self._initialized:
            return

        # Ensure log directory exists
        os.makedirs(self._log_dir, exist_ok=True)

        # Create log file if it doesn't exist
        if not os.path.exists(self._log_file):
            async with aiofiles.open(self._log_file, mode="w") as f:
                await f.write("")

        self._initialized = True
        logger.info(f"[Logger] Initialized. Writing to: {self._log_file}")

    async def log_event(
        self,
        session: AttackerSession,
        input_received: str,
        ai_response: str,
        extra_fields: Optional[dict] = None,
    ) -> None:
        """
        Log a single honeypot interaction event as flat JSON.

        Args:
            session: The attacker's session containing IP, port, service, and ID.
            input_received: The exact input from the attacker.
            ai_response: The response generated by the AI/service.
            extra_fields: Optional additional fields to include in the log entry.
        """
        if not self._initialized:
            await self.initialize()

        # Build the flat JSON log entry
        entry = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "attacker_ip": session.attacker_ip,
            "attacker_port": session.attacker_port,
            "service_targeted": session.service,
            "input_received": input_received,
            "ai_response": ai_response,
            "session_id": session.session_id,
        }

        # Merge any extra fields (threat intel, metadata, etc.)
        if extra_fields:
            entry.update(extra_fields)

        # Write to log file with rotation check
        async with self._lock:
            await self._check_rotation()

            try:
                async with aiofiles.open(self._log_file, mode="a") as f:
                    json_line = json.dumps(entry, ensure_ascii=False) + "\n"
                    await f.write(json_line)
                    self._event_count += 1
            except IOError as e:
                logger.error(f"[Logger] Failed to write log entry: {e}")

    async def log_threat_intel(
        self,
        session: AttackerSession,
        threat_type: str,
        indicator: str,
        full_command: str,
        severity: str = "medium",
    ) -> None:
        """
        Log a threat intelligence indicator as a separate enriched entry.

        Args:
            session: The attacker's session.
            threat_type: Type of threat (url_download, reverse_shell, etc.).
            indicator: The specific indicator (URL, pattern, etc.).
            full_command: The complete command that triggered detection.
            severity: Threat severity level.
        """
        await self.log_event(
            session=session,
            input_received=full_command,
            ai_response="(threat captured - simulated response provided)",
            extra_fields={
                "event_type": "threat_intel",
                "threat_type": threat_type,
                "indicator": indicator,
                "severity": severity,
            },
        )

    async def log_auth_attempt(
        self,
        session: AttackerSession,
        username: str,
        password: str,
        success: bool,
    ) -> None:
        """
        Log an authentication attempt.

        Args:
            session: The attacker's session.
            username: Attempted username.
            password: Attempted password.
            success: Whether authentication succeeded.
        """
        await self.log_event(
            session=session,
            input_received=f"AUTH: {username}:{password}",
            ai_response=f"{'accepted' if success else 'rejected'}",
            extra_fields={
                "event_type": "auth_attempt",
                "auth_username": username,
                "auth_success": success,
            },
        )

    async def log_session_start(self, session: AttackerSession) -> None:
        """Log the start of a new attacker session."""
        await self.log_event(
            session=session,
            input_received="(session started)",
            ai_response="(connection accepted)",
            extra_fields={"event_type": "session_start"},
        )

    async def log_session_end(
        self, session: AttackerSession, reason: str = "normal"
    ) -> None:
        """Log the end of an attacker session."""
        await self.log_event(
            session=session,
            input_received="(session ended)",
            ai_response=f"(disconnected: {reason})",
            extra_fields={
                "event_type": "session_end",
                "disconnect_reason": reason,
                "total_commands": session.request_count,
            },
        )

    async def _check_rotation(self) -> None:
        """
        Check if the log file needs to be rotated based on size.
        Rotates by renaming the current file with a timestamp suffix.
        """
        try:
            if not os.path.exists(self._log_file):
                return

            file_size = os.path.getsize(self._log_file)
            if file_size >= self._max_size_bytes:
                # Generate rotation filename with timestamp
                timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
                base, ext = os.path.splitext(self._log_file)
                rotated_name = f"{base}_{timestamp}{ext}"

                # Rename current file
                os.rename(self._log_file, rotated_name)
                logger.info(
                    f"[Logger] Log rotated: {self._log_file} -> {rotated_name} "
                    f"(size: {file_size / 1024 / 1024:.1f}MB)"
                )

                # Create fresh log file
                async with aiofiles.open(self._log_file, mode="w") as f:
                    await f.write("")

        except OSError as e:
            logger.error(f"[Logger] Rotation error: {e}")

    @property
    def event_count(self) -> int:
        """Return total number of events logged this session."""
        return self._event_count

    @property
    def log_file_path(self) -> str:
        """Return the current log file path."""
        return self._log_file


# =============================================================================
# Console Logging Setup
# =============================================================================

def setup_console_logging(level: int = logging.INFO) -> None:
    """
    Configure console logging with a clean, readable format.
    Sets up the root logger and all aegistrap sub-loggers.
    """
    # Create formatter
    formatter = logging.Formatter(
        fmt="%(asctime)s | %(levelname)-8s | %(name)-20s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    # Console handler
    console_handler = logging.StreamHandler()
    console_handler.setLevel(level)
    console_handler.setFormatter(formatter)

    # Configure root logger
    root_logger = logging.getLogger()
    root_logger.setLevel(level)

    # Remove existing handlers to avoid duplicates
    root_logger.handlers.clear()
    root_logger.addHandler(console_handler)

    # Suppress noisy third-party loggers
    logging.getLogger("asyncssh").setLevel(logging.WARNING)
    logging.getLogger("aiohttp").setLevel(logging.WARNING)
    logging.getLogger("aiohttp.access").setLevel(logging.WARNING)


# =============================================================================
# Module-level singleton instance
# =============================================================================
structured_logger = StructuredLogger()


async def log_interaction(
    session: AttackerSession,
    input_received: str,
    ai_response: str,
) -> None:
    """
    Convenience function for logging interactions.
    Used as the log_callback across all services.

    Args:
        session: The attacker session.
        input_received: Raw input from attacker.
        ai_response: Generated response.
    """
    await structured_logger.log_event(
        session=session,
        input_received=input_received,
        ai_response=ai_response,
    )
